import { useState } from "react";
import { Cpu, Database, GitBranch } from "lucide-react";

type Artifact = { model_id: string; architecture: string; parameter_count: number; status: string; evidence_status: string };
type Forecast = { model_version: string; model_status: string; georeferenced: false; frames: { lead_minutes: number; width: number; height: number; cells: { cell_id: string }[] }[] };
type Modality = { fusion_mode: string; model_input_channels: string[]; modalities: { source_id: string; role: string; availability: string; reason: string }[] };

export function AIPipelineWorkspace({ artifacts, forecast, modalities, loadModel, error }: {
  artifacts: Artifact[]; forecast: Forecast | null; modalities: Modality | null; loadModel: () => void; error: string | null;
}) {
  const [lead, setLead] = useState(5);
  const frame = forecast?.frames.find((item) => item.lead_minutes === lead);
  return <div className="h-full min-h-0 overflow-y-auto p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">AI pipeline & evidence inspector</h2><p className="mt-1 text-xs text-slate-400">Registered architecture, actual tensor flow, and provenance gates.</p></div><button type="button" onClick={loadModel} className="border border-cyan-700 bg-cyan-900/30 px-3 py-2 text-xs text-cyan-100">{forecast ? "Refresh model view" : "Load ConvLSTM inference"}</button></div>
    <div className="mt-4 grid gap-3 lg:grid-cols-3"><section className="border border-slate-700 bg-[#0f172a] p-4"><div className="flex items-center gap-2 text-cyan-300"><Database size={16} /><h3 className="text-xs font-semibold uppercase">Context input</h3></div><p className="mt-4 font-mono text-lg text-slate-100">13 × 384 × 384</p><p className="mt-1 text-xs text-slate-400">SEVIR VIL / one channel / U.S. benchmark pixel grid</p><p className="mt-3 font-mono text-[11px] text-amber-300">{modalities?.fusion_mode ?? "LOADING"}</p></section><section className="border border-slate-700 bg-[#0f172a] p-4"><div className="flex items-center gap-2 text-cyan-300"><Cpu size={16} /><h3 className="text-xs font-semibold uppercase">Inference</h3></div><p className="mt-4 font-mono text-sm text-slate-100">{artifacts.find((item) => item.architecture.includes("ConvLSTM"))?.architecture ?? "LightweightConvLSTM"}</p><p className="mt-2 font-mono text-xs text-slate-400">{forecast?.model_version ?? "CHECKPOINT NOT LOADED"}</p><p className="mt-2 font-mono text-[11px] text-amber-300">UNVALIDATED_PROTOTYPE</p></section><section className="border border-slate-700 bg-[#0f172a] p-4"><div className="flex items-center gap-2 text-cyan-300"><GitBranch size={16} /><h3 className="text-xs font-semibold uppercase">Prediction output</h3></div><p className="mt-4 font-mono text-lg text-slate-100">12 × 384 × 384</p><p className="mt-1 text-xs text-slate-400">T+5 to T+60 / display downsample {frame ? `${frame.width} × ${frame.height}` : "pending"}</p><p className="mt-3 font-mono text-[11px] text-amber-300">NO WGS84 / LOCATION ETA NOT_COMPUTABLE</p></section></div>
    <div className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1fr)_340px]"><section className="border border-slate-700 bg-[#0f172a] p-4"><h3 className="text-xs font-semibold uppercase text-slate-300">Inferred cell counts by lead</h3>{forecast ? <><input type="range" min={5} max={60} step={5} value={lead} onChange={(event) => setLead(Number(event.target.value))} aria-label="AI forecast lead" className="mt-5 w-full accent-cyan-400" /><div className="mt-3 flex justify-between font-mono text-xs"><span>T+{lead}m</span><span>{frame?.cells.length ?? 0} pixel-space cells</span></div><div className="mt-4 grid grid-cols-12 gap-1">{forecast.frames.map((item) => <button key={item.lead_minutes} type="button" title={`T+${item.lead_minutes}: ${item.cells.length} cells`} onClick={() => setLead(item.lead_minutes)} className={`h-10 border ${lead === item.lead_minutes ? "border-cyan-500 bg-cyan-900/40" : "border-slate-700 bg-slate-800/40"}`}><span className="font-mono text-[9px]">{item.cells.length}</span></button>)}</div></> : <p className="mt-5 font-mono text-xs text-slate-500">{error ?? "Select load to run registered inference."}</p>}</section><section className="border border-slate-700 bg-[#0f172a] p-4"><h3 className="text-xs font-semibold uppercase text-slate-300">Physical attribution</h3><p className="mt-4 font-mono text-sm text-amber-300">NOT_COMPUTABLE</p><p className="mt-2 text-xs leading-5 text-slate-400">The current checkpoint is VIL-only and has no calibrated physical attribution output. No attention weight or feature importance percentage is claimed.</p><div className="mt-4 border-t border-slate-700 pt-3">{modalities?.modalities.map((item) => <p key={item.source_id} className="mb-2 font-mono text-[10px] text-slate-400">{item.source_id}: {item.role} / {item.availability}</p>)}</div></section></div>
  </div>;
}
