import { DatabaseZap, LockKeyhole, Radio } from "lucide-react";
import type { IMDBridgeStatus } from "../types/analytics";
import type { EvidenceStatus } from "../types/location";

type Source = { source_id: string; name: string; modality: string; availability: string; quality_status: string; evidence_status: EvidenceStatus; provenance: string };
type Modality = { fusion_mode: string; model_input_channels: string[]; modalities: { source_id: string; availability: string; role: string; reason: string }[] };

export function DataSourcesWorkspace({ sources, bridge, modalities }: { sources: Source[]; bridge: IMDBridgeStatus | null; modalities: Modality | null }) {
  return <div className="h-full min-h-0 overflow-y-auto p-4"><div className="flex items-center gap-2"><DatabaseZap size={19} className="text-cyan-300" /><h2 className="text-lg font-semibold">Data sources & IMD bridge</h2></div><p className="mt-1 text-xs text-slate-400">Connection readiness is separate from observation availability. No IMD or MOSDAC product is currently ingested.</p>
    <div className="mt-4 grid gap-3 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="border border-slate-700 bg-[#0f172a]"><div className="flex items-center gap-2 border-b border-slate-700 px-4 py-3"><Radio size={16} className="text-cyan-300" /><h3 className="text-xs font-semibold uppercase">Replay and sensor inventory</h3></div><div className="divide-y divide-slate-800">{sources.map((source) => <div key={source.source_id} className="grid gap-1 px-4 py-3 sm:grid-cols-[minmax(0,1fr)_130px]"><div><p className="text-sm text-slate-100">{source.name}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{source.source_id} / {source.modality} / {source.quality_status}</p><p className="mt-1 text-[11px] text-slate-500">{source.provenance}</p></div><span className={`font-mono text-[10px] ${source.availability === "AVAILABLE" ? "text-emerald-300" : "text-amber-300"}`}>{source.availability}<br />{source.evidence_status}</span></div>)}</div></section><section className="border border-slate-700 bg-[#0f172a] p-4"><div className="flex items-center gap-2"><LockKeyhole size={16} className="text-amber-300" /><h3 className="text-xs font-semibold uppercase">IMD DWR / MOSDAC API</h3></div><p className="mt-4 font-mono text-sm text-amber-300">{bridge?.state ?? "STATUS UNAVAILABLE"}</p><p className="mt-2 text-xs text-slate-400">Disconnected. Radar credentials, product licensing and data-quality checks are pending.</p><ol className="mt-4 space-y-2 border-t border-slate-700 pt-3">{bridge?.pipeline_steps.map((step, index) => <li key={step} className="font-mono text-[11px] text-slate-300">{index + 1}. {step}</li>)}</ol><p className="mt-4 text-[11px] text-amber-300">{bridge?.required_gates.join(" / ")}</p></section></div>
    <section className="mt-3 border border-slate-700 bg-[#0f172a] p-4"><h3 className="text-xs font-semibold uppercase">Multimodal alignment</h3><p className="mt-2 font-mono text-xs text-cyan-300">{modalities?.fusion_mode ?? "LOADING"} / MODEL INPUT {modalities?.model_input_channels.join(", ") ?? "--"}</p><div className="mt-3 grid gap-2 md:grid-cols-2">{modalities?.modalities.map((item) => <div key={item.source_id} className="border border-slate-800 p-3"><p className="font-mono text-xs">{item.source_id} / {item.role}</p><p className="mt-1 text-[11px] text-slate-400">{item.reason}</p></div>)}</div></section>
  </div>;
}
